CREATE TABLE IF NOT EXISTS "shpe-website-2025_alumni" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "shpe-website-2025_alumni_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"first_name" varchar(100),
	"last_name" varchar(100),
	"grad_year" varchar(100),
	"image" varchar(2048),
	"linkedIn" text,
	"position" "position" DEFAULT 'Member'
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "shpe-website-2025_cart" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "shpe-website-2025_cart_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"created_at" timestamp with time zone DEFAULT now(),
	"member_uuid" uuid NOT NULL,
	"product_id" integer NOT NULL,
	"quantity" integer NOT NULL,
	CONSTRAINT "shpe-website-2025_cart_member_uuid_product_id_unique" UNIQUE("member_uuid","product_id"),
	CONSTRAINT "cart_member_product_unique" UNIQUE("member_uuid","created_at")
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "shpe-website-2025_members" (
	"uuid" uuid PRIMARY KEY NOT NULL,
	"ucf_id" integer NOT NULL,
	"first_name" varchar(100),
	"last_name" varchar(100),
	"email" varchar(100) NOT NULL,
	"image" varchar(2048),
	"resume" varchar(2048),
	"is_member" boolean DEFAULT false,
	"position" "position" DEFAULT 'Member',
	CONSTRAINT "shpe-website-2025_members_ucf_id_unique" UNIQUE("ucf_id"),
	CONSTRAINT "shpe-website-2025_members_email_unique" UNIQUE("email")
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "shpe-website-2025_products" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "shpe-website-2025_products_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(100),
	"category" varchar(100) NOT NULL,
	"image" varchar(2048),
	"description" varchar(2048),
	"price" real NOT NULL,
	"stock" integer,
	CONSTRAINT "shpe-website-2025_products_category_unique" UNIQUE("category")
);
--> statement-breakpoint
ALTER TABLE "shpe-website-2025_cart" ADD CONSTRAINT "shpe-website-2025_cart_member_uuid_shpe-website-2025_members_uuid_fk" FOREIGN KEY ("member_uuid") REFERENCES "public"."shpe-website-2025_members"("uuid") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "shpe-website-2025_cart" ADD CONSTRAINT "shpe-website-2025_cart_product_id_shpe-website-2025_products_id_fk" FOREIGN KEY ("product_id") REFERENCES "public"."shpe-website-2025_products"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint